[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
upload_speed = 460800

; The PlatformIO board manifest for esp32-s3-devkitc-1 defaults to N8/no PSRAM.
; This project targets ESP32-S3N16R8: 16 MB flash + 8 MB OPI PSRAM.
board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
